language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer

matrix:
  exclude:
    - php: '5.5'
        env: LARAVEL_VERSION="dev-master"
  allow_failures:
    - php: nightly
    - env: LARAVEL_VERSION="dev-master"

env:
    - LARAVEL_VERSION="5.1.*"
    - LARAVEL_VERSION="5.2.*"
    - LARAVEL_VERSION="dev-master"

script: phpunit --coverage-text

install:
    - composer self-update
    - composer require --no-update illuminate/http:${LARAVEL_VERSION}
    - if [[ "$LARAVEL_VERSION" == "dev-master" ]]; then sed -i "s/\"MIT\"/\"MIT\",\"minimum-stability\":\"dev\"/g" composer.json; fi
    - composer update --prefer-source

notifications:
    email: jakub.trunecek@gmail.com
