language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

env:
  - LARAVEL_VERSION="5.1.x",STABILITY=stable
  - LARAVEL_VERSION="5.2.x",STABILITY=stable
  - LARAVEL_VERSION="dev-master",STABILITY=dev

script: phpunit --coverage-text

install:
   - composer require illuminate/http:${LARAVEL_VERSION}
   - composer config minimum-stability ${STABILITY}
   - composer install --dev