language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

env:
  - LARAVEL_VERSION="5.1.x"
  - LARAVEL_VERSION="5.2.x"
  - LARAVEL_VERSION="dev-master"

install:
   - composer require illuminate/http:${LARAVEL_VERSION}
   - composer install